figsize: 800
naip_dir: /home/jmbillson/Python/CropSight/CropSightPlus/naip
cdl_dir: /home/jmbillson/Python/CropSight/CropSightPlus/cdl/cdl
ae_dir: /home/jmbillson/Python/CropSight/CropSightPlus/alpha_earth
segment_dir: /home/jmbillson/Python/CropSight/CropSightPlus/mask2former
dst_dir: /home/jmbillson/Python/CropSight/CropSightPlus/fields
sample_id: random