figsize: 800
naip_dir: /Users/anant_gupta/Documents/DataAnnotation/Cropsight/naip-100
cdl_dir: /Users/anant_gupta/Documents/DataAnnotation/Cropsight/cdl
ae_dir: /Users/anant_gupta/Documents/DataAnnotation/Cropsight/alpha_earth-100
segment_dir: /Users/anant_gupta/Documents/DataAnnotation/Cropsight/sam-100
dst_dir: /Users/anant_gupta/Documents/DataAnnotation/Cropsight/manual
sample_id: random